name: Cache Dependencies

on:
  push:
    branches:
      - master

jobs:
  cache-dependencies:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 16
        package:
          - firebase
          - firebase-auth
          - firebase-cloud-messaging
    runs-on: ${{ matrix.os }}
    name: Cache Dependencies (${{ matrix.package }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calculate path filters
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            ${{ matrix.package }}:
              - '${{ matrix.package }}/**/*'
      - name: Setup Node.js for use with actions
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup dependency cache
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ matrix.package }}/node_modules
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles(env.PACKAGE_LOCK_PATH) }}
        env:
          PACKAGE_LOCK_PATH: ${{ matrix.package }}/package-lock.json
      - name: Setup .npmrc
        if: ${{ steps.filter.outputs[matrix.package] == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        working-directory: ${{ matrix.package }}
      - name: Install dependencies
        if: ${{ steps.filter.outputs[matrix.package] == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
        working-directory: ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
