name: Cache Dependencies

on:
  push:
    branches:
      - master

jobs:
  cache-dependencies:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 16
        package:
          - firebase
    runs-on: ${{ matrix.os }}
    name: Cache Dependencies (${{ matrix.package }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calculate path filters
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            firebase:
              - 'firebase/**/*'
      - name: Setup Node.js for use with actions
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup dependency cache
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('{{ matrix.package }}/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.filter.outputs[matrix.package] == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
        working-directory: ${{ matrix.package }}
