name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 16
        package:
          - firebase
          - firebase-auth
          - firebase-cloud-messaging
    name: CI (${{ matrix.package }})
    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calculate path filters
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            ${{ matrix.package }}:
              - '${{ matrix.package }}/**/*'
      - name: Setup Node.js for use with actions
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup dependency cache
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.package }}/node_modules
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles(env.PACKAGE_LOCK_PATH) }}
        env:
          PACKAGE_LOCK_PATH: ${{ matrix.package }}/package-lock.json
      - name: Setup .npmrc
        if: ${{ steps.filter.outputs[matrix.package] == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        working-directory: ${{ matrix.package }}
      - name: Install dependencies
        if: ${{ steps.filter.outputs[matrix.package] == 'true' && steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
        working-directory: ${{ matrix.package }}
      - name: Lint code
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        run: npm run lint:code
        working-directory: ${{ matrix.package }}
      - name: Lint styling
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        run: npm run lint:style
        working-directory: ${{ matrix.package }}
      - name: Run unit tests
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        run: npm run test:unit:coverage
        working-directory: ${{ matrix.package }}
      - name: Build
        if: ${{ steps.filter.outputs[matrix.package] == 'true' }}
        run: npm run build
        working-directory: ${{ matrix.package }}
